Replacing QDoubleSpinBoxes by QGSDoubleSpinBoxes due to error with reading plugin in Windows 10 ==> AttributeError: 'QDoubleSpinBox' object has no attribute 'setStepType'